project:
  type: website
  output-dir: docs

website:
  title: "DDOmicsLab"
  page-navigation: true
  back-to-top-navigation: true
  page-footer: "Copyright 2023, Dhiraj P. Dhotre" 
  twitter-card: true
  navbar:
    background: secondary
    search: true
    left:
      - dhiraj.qmd
      - research.qmd
      - publications.qmd
      - team.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

