project:
  type: website
  output-dir: docs

website:
  title: ""
  page-navigation: true
  back-to-top-navigation: true
  page-footer: "Copyright 2023, Dhiraj P. Dhotre" 
  twitter-card:
    creator: "@DDOmicsLab"
  open-graph: true
  navbar:
    logo: img/logo4.jpeg
    background: secondary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Dr. Dhiraj Dhotre"
        file: people/lab-members/dhiraj.qmd
      - text: "Research"
        file: research.qmd
      - publications.qmd
      - text: "People"
        file: people.qmd
    right: 
      - icon: twitter
        href: "https://twitter.com/DDOmicsLab"
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

