---
title: "Publications"
filters:
  - openlinksinnewpage
---

## 2023

::: {style="text-align: justify"}
-   Ahmed, Anam, Kunal Dixit, Alka Singh, Ashish Agarwal, Wajiha Mehtab, Shubham Prasad, Mahendra Singh Rajput et al. "Sieving out non-celiac gluten sensitivity amongst patients with irritable bowel syndrome." *Digestive and Liver Disease* (2023).

-   Kadam, Pratik, Mitesh Khisti, Varun Ravishankar, Vitthal Barvkar, **Dhiraj Dhotre**, Avinash Sharma, Yogesh Shouche, and Smita Zinjarde. "Recent advances in production and applications of ectoine, a compatible solute of industrial relevance." *Bioresource Technology* (2023): 130016.

-   Singh, Kumar Siddharth, Abhishek Keer, Aakib Zed, Rahila Jasmeen, Kamini Mishra, Neha Mourya, Dhiraj Paul, **Dhiraj Dhotre**, and Yogesh Shouche. "High antibiotic resistance in Indian sewage shows distinct trends and might be disjoint from in-situ antibiotic levels." *Water, Air, & Soil Pollution* 234, no. 7 (2023): 467.

-   Dixit, Kunal, Anam Ahmed, Alka Singh, Wajiha Mehtab, Ashish Chauhan, Vineet Ahuja, Yogesh Shouche, **Dhiraj Dhotre**, and Govind K. Makharia. "Mo1869 SITE-SPECIFIC MICROBIAL SIGNATURES IN NON-CELIAC GLUTEN SENSITIVITY AND IRRITABLE BOWEL SYNDROME." *Gastroenterology* 164, no. 6 (2023): S-923.

-   Chaudhari, Diptaraj, Shashi Kiran, Ashish Choudhary, Kris Silveira, Nitin Narwade, **Dhiraj Dhotre**, Jabeena Khazir, Bilal Ahmad Mir, Yogesh S. Shouche, and Praveen Rahi. "Prokaryotic communities adapted to microhabitats on the Indian lotus (Nelumbo nucifera) growing in the high-altitude urban Dal Lake." *International Microbiology* 26, no. 2 (2023): 257-267.

-   Ghare, Uma, Simran Narvekar, Tushar Lodha, Rubiya Mallebhari, Syed Dastager, Vitthal T. Barvkar, **Dhiraj Dhotre**, Nitin R. Karmalkar, and Anupama A. Pable. "Bacterial Communities and Diversity of Western Ghats Soil: A Study of a Biodiversity Hotspot." *Current Microbiology* 80, no. 4 (2023): 108.

-   Singh, Kumar Siddharth, Dhiraj Paul, Abhishek Gupta, **Dhiraj Dhotre**, Frank Klawonn, and Yogesh Shouche. "Indian sewage microbiome has unique community characteristics and potential for population-level disease predictions." *Science of The Total Environment* 858 (2023): 160178.

-   Kumkar, Shital N., Ekta E. Kamble, Nikeeta S. Chavan, **Dhiraj P. Dhotre**, and Karishma R. Pardesi. "Corrigendum: Diversity of resistant determinants, virulence factors, and mobile genetic elements in Acinetobacter baumannii from India: A comprehensive in silico genome analysis." *Frontiers in Cellular and Infection Microbiology* 12 (2023): 1130394.
:::

## 2022

::: {style="text-align: justify"}
-   Kumkar, Shital N., Ekta E. Kamble, Nikeeta S. Chavan, **Dhiraj P. Dhotre**, and Karishma R. Pardesi. "Diversity of resistant determinants, virulence factors, and mobile genetic elements in Acinetobacter baumannii from India: A comprehensive in silico genome analysis." *Frontiers in Cellular and Infection Microbiology* 12 (2022): 997897.

-   Kadam, Pratik, Swapnil Kajale, Avinash Sharma, **Dhiraj Dhotre**, Vitthal Barvkar, Yogesh Shouche, and Smita Zinjarde. "Whole-Genome Sequencing of the Tropical Marine Bacterium Nocardiopsis dassonvillei NCIM 5124, Containing the Ectoine Biosynthesis Gene Cluster ectABC." *Microbiology Resource Announcements* 11, no. 10 (2022): e00435-22.

-   Spehlmann, Martina E., **Dhiraj P. Dhotre**, Nesrin Schmiedel, Nikita Chavan, Corinna Bang, and Ashraf Y. Rangrez. "Dataset of ileum bacterial diversity in mice after heart failure due to pressure overload." *Data in Brief* 44 (2022): 108498.

-   Singh, Abhishek, Atahar Husein, Salomi Singh, Vikas Ghattargi, **Dhiraj Dhotre**, Yogesh S. Shouche, Stacy Colaco et al. "False-positive detection of Group B Streptococcus (GBS) in chromogenic media (Strep B Carrot Broth) due to presence of Enterococcus faecalis in High Vaginal swabs." *Journal of Medical Microbiology* 71, no. 8 (2022): 001577.

-   Chauhan, Nar Singh, Neetha Joseph, Shraddha Shaligram, Nikita Chavan, Amaraja Joshi, **Dhiraj Dhotre**, Tushar Lodha, and Yogesh Shouche. "Paenibacillus oleatilyticus sp. nov., isolated from soil." *Archives of Microbiology* 204, no. 8 (2022): 516.

-   Alai, Shweta, Manish Gautam, Sonali Palkar, Jitendra Oswal, Sunil Gairola, and **Dhiraj P. Dhotre.** "Characterization of Bordetella pertussis Strains Isolated from India." *Pathogens* 11, no. 7 (2022): 794.

-   Sagar, Isita, Yogesh Nimonkar, **Dhiraj Dhotre**, Yogesh Shouche, Dilip Ranade, Sahabram Dewala, and Om Prakash. "A Microcosm Model for the Study of Microbial Community Shift and Carbon Emission from Landfills." *Indian Journal of Microbiology* (2022): 1-9.

-   Rahi, Praveen, Diptaraj Chaudhari, Shashi Kiran, Ashish Choudhary, Kris Silveira, Nitin Narwade, **Dhiraj Dhotre**, Jabeena Khazir, Bilal Ahmad Mir, and Yogesh S. Shouche. "Prokaryotic communities adapted to microhabitats on the Indian lotus (Nelumbo nucifera) growing in the high-altitude urban Dal Lake." (2022).

-   Spehlmann, Martina E., Ashraf Y. Rangrez, **Dhiraj P. Dhotre**, Nesrin Schmiedel, Nikita Chavan, Corinna Bang, Oliver J. Müller et al. "Heart failure severity closely correlates with intestinal dysbiosis and subsequent metabolomic alterations." *Biomedicines* 10, no. 4 (2022): 809.

-   Spehlmann, Martina E., Ashraf Y. Rangrez, **Dhiraj P. Dhotre**, Nesrin Schmiedel, Nikita Chavan, Corinna Bang, Oliver J. Müller et al. "Heart failure severity closely correlates with intestinal dysbiosis and subsequent metabolomic alterations." *Biomedicines* 10, no. 4 (2022): 809.

-   Alai, S., M. Gautam, S. Palkar, J. Oswal, S. Gairola, and **D. P. Dhotre.** "Characterization of Bordetella pertussis Strains Isolated from India. Pathogens 2022, 11, 794." (2022).

-   Ghattargi, Vikas C., Yogesh S. Shouche, Prashant K. Dhakephalkar, Praveen Rao, Venkata Ramana, **Dhiraj P. Dhotre**, and Vikram B. Lanjekar. "Probiotics: A Mainstream Therapy for the Disease Suppression." (2022): 257-273.
:::

## 2021

::: {style="text-align: justify"}
-   Mane, Sarika, Kunal K. Dixit, Nidhi Lathwal, **Dhiraj Dhotre**, Priyadarshani Kadus, Yogesh S. Shouche, and Supriya Bhalerao. "Rectal administration of buttermilk processed with medicinal plants alters gut microbiome in obese individuals." *Journal of Diabetes & Metabolic Disorders* 20, no. 2 (2021): 1415-1427.

-   Mongad, Dattatray S., Nikeeta S. Chavan, Nitin P. Narwade, Kunal Dixit, Yogesh S. Shouche, and **Dhiraj P. Dhotre.** "MicFunPred: A conserved approach to predict functional profiles from 16S rRNA gene sequence data." *Genomics* 113, no. 6 (2021): 3635-3643.

-   Dixit, Kunal, Diptaraj Chaudhari, **Dhiraj Dhotre**, Yogesh Shouche, and Sunil Saroj. "Restoration of dysbiotic human gut microbiome for homeostasis." *Life Sciences* 278 (2021): 119622.

-   Shaligram, Shraddha, Nitin P. Narwade, Shreyas V. Kumbhare, Manobjyoti Bordoloi, Kashyap J. Tamuli, Shyamalendu Nath, T. Parimelazhagan et al. "Integrated Genomic and Functional Characterization of the Anti-diabetic Potential of Arthrobacter sp. SW1." *Current Microbiology* 78, no. 7 (2021): 2577-2588.

-   Agarwal, Dhiraj M., **Dhiraj P. Dhotre**, Shreyas V. Kumbhare, Akshay H. Gaike, Bill B. Brashier, Yogesh S. Shouche, Sanjay K. Juvekar, and Sundeep S. Salvi. "Disruptions in oral and nasal microbiota in biomass and tobacco smoke associated chronic obstructive pulmonary disease." *Archives of Microbiology* 203 (2021): 2087-2099.

-   Kaushik, Rishabh, Maharaj K. Pandit, Laura A. Meyerson, Diptaraj S. Chaudhari, Meesha Sharma, **Dhiraj Dhotre**, and Yogesh S. Shouche. "Contrasting composition, diversity and predictive metabolic potential of the rhizobacterial microbiomes associated with native and invasive Prosopis congeners." *Current Microbiology* 78 (2021): 2051-2060.

-   Dixit, Kunal, Dimple Davray, Diptaraj Chaudhari, Pratik Kadam, Rudresh Kshirsagar, Yogesh Shouche, **Dhiraj Dhotre**, and Sunil D. Saroj. "Benchmarking of 16S rRNA gene databases using known strain sequences." *Bioinformation* 17, no. 3 (2021): 377.

-   Assad, Rezwana, Zafar Ahmad Reshi, Showkat Hamid Mir, Irfan Rashid, Yogesh Shouche, and **Dhiraj Dhotre**. "Bioprospecting appraisal of Himalayan pindrow fir for pharmacological applications." In *Phytomedicine*, pp. 461-482. Academic Press, 2021.
:::

## 2020

::: {style="text-align: justify"}
-   Chaudhari, Diptaraj S., **Dhiraj P. Dhotre**, Kunal Jani, Avinash Sharma, Yadvinder Singh, Yogesh S. Shouche, and Praveen Rahi. "Bacterial communities associated with the biofilms formed in high-altitude brackish water Pangong Tso located in the Himalayan Plateau." *Current Microbiology* 77 (2020): 4072-4084.

-   Alai, Shweta, Vikas C. Ghattargi, Manish Gautam, Krunal Patel, Shrikant P. Pawar, **Dhiraj P. Dhotre**, Umesh Shaligram, and Sunil Gairola. "Comparative genomics of whole-cell pertussis vaccine strains from India." *BMC genomics* 21 (2020): 1-15.

-   Kirdat, Kiran, Bhavesh Tiwarekar, Vipool Thorat, Nitin Narawade, **Dhiraj Dhotre**, Shivaji Sathe, Yogesh Shouche, and Amit Yadav. "Draft genome sequences of two phytoplasma strains associated with sugarcane grassy shoot (SCGS) and bermuda grass white leaf (BGWL) diseases." *Molecular plant-microbe interactions* 33, no. 5 (2020): 715-717.

-   Jena, Jyotsnarani, Nitin Narwade, Trupti Das, **Dhiraj Dhotre**, Ujjaini Sarkar, and Yogesh Souche. "Treatment of industrial effluents and assessment of their impact on the structure and function of microbial diversity in a unique Anoxic-Aerobic sequential batch reactor (AnASBR)." *Journal of environmental management* 261 (2020): 110241.

-   Gaike, Akshay H., Dhiraj Paul, Shrikant Bhute, **Dhiraj P. Dhotre**, Pranav Pande, Smitha Upadhyaya, Yugandhar Reddy et al. "The gut microbial diversity of newly diagnosed diabetics but not of prediabetics is significantly different from that of healthy nondiabetics." *Msystems* 5, no. 2 (2020): e00578-19.

-   Chaudhari, Diptaraj S., **Dhiraj P. Dhotre**, Dhiraj M. Agarwal, Akshay H. Gaike, Devika Bhalerao, Parmeshwar Jadhav, Dattatray Mongad et al. "Gut, oral and skin microbiome of Indian patrilineal families reveal perceptible association with age." *Scientific Reports* 10, no. 1 (2020): 5685.

-   Joshi, Amaraja, Sonia Thite, **Dhiraj Dhotre**, Manju Moorthy, Neetha Joseph, V. Venkata Ramana, and Yogesh Shouche. "Nitrincola tapanii sp. nov., a novel alkaliphilic bacterium from An Indian Soda Lake." *International journal of systematic and evolutionary microbiology* 70, no. 2 (2020): 1106-1111.

-   Gaike, A. H., D. Paul, S. Bhute, **D. P. Dhotre**, P. Pande, S. Upadhyaya, Y. Reddy et al. "The gut microbial diversity of newly diagnosed diabetics but not of prediabetics is significantly different from that of healthy nondiabetics. mSystems 5: e00578-19." (2020).

-   Assad, Rezwana, Zafar Ahmad Reshi, Irfan Rashid, Yogesh Shouche, and **Dhiraj Dhotre.** "Role of ectomycorrhizal biotechnology in pesticide remediation." *Bioremediation and Biotechnology, Vol 3: Persistent and Recalcitrant Toxic Substances* (2020): 315-330.
:::

## 2019

::: {style="text-align: justify"}
-   **DHOTRE, DHIRAJ P.**, SHREYAS V. KUMBHARE, VILAS P. SINKAR, and YOGESH S. SHOUCHE. "Human gut microbiome research in India: A retrospect and future opportunities." In *Proc Indian Natn Sci Acad*, vol. 85, no. 4, pp. 1051-1066. 2019.

-   Mane, Sarika, Kunal Dixit, Nidhi Lathwal, **Dhiraj Dhotre**, Yogesh Shouche, Priyadarshani Kadus, and Supriya Bhalerao. "Per rectum administration of buttermilk processed with medicinal plants alters gut microbiota in obese individuals." In *JOURNAL OF GASTROENTEROLOGY AND HEPATOLOGY*, vol. 34, pp. 272-272. 111 RIVER ST, HOBOKEN 07030-5774, NJ USA: WILEY, 2019.

-   Matharu, Dollwin, **Dhiraj Dhotre**, Nagalakshmi Balasubramanian, Namrata Pawar, Sneha Sagarkar, and Amul Sakharkar. "Repeated mild traumatic brain injury affects microbial diversity in rat jejunum." *Journal of biosciences* 44 (2019): 1-12.

-   Chaudhari, Diptaraj, **Dhiraj Dhotre**, Dhiraj Agarwal, Arun Gondhali, Anand Nagarkar, Vikas Lad, Ulhas Patil, Sanjay Juvekar, Vilas Sinkar, and Yogesh Shouche. "Understanding the association between the human gut, oral and skin microbiome and the Ayurvedic concept of prakriti." *Journal of Biosciences* 44 (2019): 1-8.

-   Auti, Asim M., Nitin P. Narwade, Neelima M. Deshpande, and **Dhiraj P. Dhotre**. "Microbiome and imputed metagenome study of crude and refined petroleum-oil-contaminated soils: Potential for hydrocarbon degradation and plant-growth promotion." *Journal of Biosciences* 44 (2019): 1-16.

-   Alai, Shweta, Vikas C. Ghattargi, Manish Gautam, **Dhiraj P. Dhotre**, Krunal Patel, Shrikant P. Pawar, Rakesh Kumar, Umesh Shaligram, Deepti Deobagkar, and Sunil Gairola. "Genome sequence of Bordetella pertussis vaccine strain BP 165." *Microbiology Resource Announcements* 8, no. 16 (2019): 10-1128.

-   Kulkarni, Abhijit S., Shreyas V. Kumbhare, **Dhiraj P. Dhotre**, and Yogesh S. Shouche. "Mining the core gut microbiome from a sample Indian population." *Indian journal of microbiology* 59 (2019): 90-95.

-   Bodkhe, Rahul, Sudarshan A. Shetty, **Dhiraj P. Dhotre**, Anil K. Verma, Khushbo Bhatia, Asha Mishra, Gurvinder Kaur et al. "Comparison of small gut and whole gut microbiota of first-degree relatives with adult celiac disease patients and controls." *Frontiers in microbiology* (2019): 164.
:::

## 2018

::: {style="text-align: justify"}
-   Ghattargi, Vikas C., Meghana A. Gaikwad, Bharati S. Meti, Yogesh S. Nimonkar, Kunal Dixit, Om Prakash, Yogesh S. Shouche, Shrikant P. Pawar, and **Dhiraj P. Dhotre**. "Comparative genome analysis reveals key genetic factors associated with probiotic property in Enterococcus faecium strains." *BMC genomics* 19, no. 1 (2018): 1-16.

-   Jani, Kunal, **Dhiraj Dhotre**, Jayashree Bandal, Yogesh Shouche, Mangesh Suryavanshi, Vinay Rale, and Avinash Sharma. "World's largest mass bathing event influences the bacterial communities of Godavari, a holy river of India." *Microbial ecology* 76 (2018): 706-718.
:::

## 2017

::: {style="text-align: justify"}
-   Shetty, Sudarshan A., Rahul Bodkhe, **Dhiraj P. Dhotre**, Anil K. Verma, Khushbo Bhatia, Asha Mishra, Gurvinder Kaur et al. "Comparison of Small Gut and Whole Gut Microbiota of First-Degree Relatives with Adult Celiac Disease Patients and Controls." *bioRxiv* (2017): 227272.

-   Chaudhari, Ashvini U., Dhiraj Paul, **Dhiraj Dhotre**, and Kisan M. Kodam. "Effective biotransformation and detoxification of anthraquinone dye reactive blue 4 by using aerobic bacterial granules." *Water Research* 122 (2017): 603-613.

-   Kumbhare, Shreyas V., Himanshu Kumar, Somak P. Chowdhury, **Dhiraj P. Dhotre**, Akihito Endo, Jaana Mättö, Arthur C. Ouwehand et al. "A cross-sectional comparative study of gut bacterial community of Indian and Finnish children." *Scientific reports* 7, no. 1 (2017): 10555.

-   Ghosh, Baishakhi, Akshay Gaike, Shreyas Kumbhare, Kanchan Pyasi, Jyoti Londhe, Vandana Vincent, Bill Brashier et al. "Induced sputum microbiome in smoker and non-smoker COPD subjects and its association with lung function in Indian subjects." (2017).

-   Agarwal, Dhiraj, **Dhiraj Dhotre**, Rutuja Patil, Yogesh Shouche, Sanjay Juvekar, and Sundeep Salvi. "Potential of health and demographic surveillance system in asthma and chronic obstructive pulmonary disease microbiome research." *Frontiers in public health* 5 (2017): 196.

-   **Dhotre, Dhiraj Prakash**, Vaheesan Rajabal, Avinash Sharma, Girish J. Kulkarni, Om Prakash, Venkata Ramana Vemuluri, Neetha Joseph, Praveen Rahi, and Yogesh S. Shouche. "Reclassification of Phycicola gilvus (Lee et al. 2008) and Leifsonia pindariensis (Reddy et al. 2008) as Microterricola gilva comb. nov. and Microterricola pindariensis comb. nov. and emended description of the genus Microterricola." *International Journal of Systematic and Evolutionary Microbiology* 67, no. 8 (2017): 2766-2772.

-   Sharma, A., D. Paul, **D. Dhotre**, K. Jani, A. Pandey, and Y. S. Shouche. "Deep sequencing analysis of bacterial community structure of Soldhar hot spring, India." *Microbiology* 86 (2017): 136-142.
:::

## 2016

::: {style="text-align: justify"}
-   Shaligram, Shraddha, Shreyas V. Kumbhare, **Dhiraj P. Dhotre**, Manohar G. Muddeshwar, Atya Kapley, Neetha Joseph, Hemant P. Purohit, Yogesh S. Shouche, and Shrikant P. Pawar. "Genomic and functional features of the biosurfactant producing Bacillus sp. AM13." *Functional & integrative genomics* 16 (2016): 557-566.

-   Bhute, Shrikant, Pranav Pande, Sudarshan A. Shetty, Rahul Shelar, Sachin Mane, Shreyas V. Kumbhare, Ashwini Gawali et al. "Molecular characterization and meta-analysis of gut microbial communities illustrate enrichment of Prevotella and Megasphaera in Indian subjects." *Frontiers in microbiology* 7 (2016): 660.

-   Joshi, Amaraja, Sonia Thite, Girish Kulkarni, **Dhiraj Dhotre**, Neetha Joseph, V. Venkata Ramana, Ashish Polkade, and Yogesh Shouche. "Nitrincola alkalisediminis s p. nov., an alkaliphilic bacterium isolated from an alkaline lake." *International Journal of Systematic and Evolutionary Microbiology* 66, no. 3 (2016): 1254-1259.
:::

## 2015

::: {style="text-align: justify"}
-   Kumbhare, Shreyas V., **Dhiraj P. Dhotre**, Sunil Kumar Dhar, Kunal Jani, Deepak A. Apte, Yogesh S. Shouche, and Avinash Sharma. "Insights into diversity and imputed metabolic potential of bacterial communities in the continental shelf of Agatti Island." *PLoS One* 10, no. 6 (2015): e0129864.

-   Shouche, Yogesh S., Abhijit S. Dighe, **Dhiraj P. Dhotre**, Milind S. Patole, and Dilip R. Ranade. "Selenomonas." *Bergey's Manual of Systematics of Archaea and Bacteria* (2015): 1-12.

-   Salunkhe, Rahul C., **Dhiraj P. Dhotre**, Bipinchandra K. Salunke, Vikas S. Patil, Vaibhav Mahale, Raymond J. Andrew, Milind S. Patole, Ketan P. Narkhede, and Yogesh S. Shouche. "Distribution and molecular characterization of Wolbachia endosymbionts in Odonata (Insecta) from Central India by multigene approach." *Current Science* (2015): 971-978.
:::

## 2014

::: {style="text-align: justify"}
-   Mahale, Kiran N., Pradyumna S. Paranjape, Nachiket P. Marathe, **Dhiraj P. Dhotre**, Somak Chowdhury, Sudarshan A. Shetty, Avinash Sharma et al. "Draft genome sequences of Yersinia pestis strains from the 1994 plague epidemic of Surat and 2002 Shimla outbreak in India." *Indian journal of microbiology* 54 (2014): 480-482.

-   Walujkar, Sandeep A., **Dhiraj P. Dhotre**, Nachiket P. Marathe, Parimal S. Lawate, Renu S. Bharadwaj, and Yogesh S. Shouche. "Characterization of bacterial community shift in human Ulcerative Colitis patients revealed by Illumina based 16S rRNA gene amplicon sequencing." *Gut pathogens* 6, no. 1 (2014): 1-11.
:::

## 2013

::: {style="text-align: justify"}
-   **Dhotre, Dhiraj Prakash**. "Comparative genome analysis of Mosquito vector." (2013).

-   Shetty, Sudarshan A., Nachiket P. Marathe, Hitendra Munot, Chakkiath Paul Antony, **Dhiraj P. Dhotre**, J. Colin Murrell, and Yogesh S. Shouche. "Draft genome sequence of Methylophaga lonarensis MPLT, a haloalkaliphilic (non-methane-utilizing) methylotroph." *Genome announcements* 1, no. 3 (2013): 10-1128.

-   Gokhale, Kaustubh, Deepak P. Patil, **Dhiraj P. Dhotre**, Rajnikant Dixit, Murlidhar J. Mendki, Milind S. Patole, and Yogesh S. Shouche. "Transcriptome analysis of Anopheles stephensi embryo using expressed sequence tags." *Journal of biosciences* 38 (2013): 301-309.

-   Kulkarni, Girish, **Dhiraj Dhotre**, Mahesh Dharne, Sudarshan Shetty, Somak Chowdhury, Vatsala Misra, Sriprakash Misra, Milind Patole, and Yogesh Shouche. "Draft genome of Ochrobactrum intermedium strain M86 isolated from non-ulcer dyspeptic individual from India." *Gut Pathogens* 5, no. 1 (2013): 1-5.
:::

## 2012

::: {style="text-align: justify"}
-   Pawar, S. P., **D. P. Dhotre**, S. A. Shetty, S. P. Chowdhury, B. L. Chaudhari, and Y. S. Shouche. "Genome sequence of Janibacter hoylei MTCC8307, isolated from the stratospheric air." (2012): 6629-6630.

-   Patil, Deepak P., **Dhiraj P. Dhotre**, Sachin G. Chavan, Armiya Sultan, Dhawal S. Jain, Vikram B. Lanjekar, Jayshree Gangawani et al. "Molecular analysis of gut microbiota in obesity among Indian individuals." *Journal of biosciences* 37 (2012): 647-657.

-   Salunke, Bipinchandra K., Rahul C. Salunkhe, **Dhiraj P. Dhotre**, Sandeep A. Walujkar, Avinash B. Khandagale, Rahul Chaudhari, Rakesh K. Chandode et al. "Determination of Wolbachia diversity in butterflies from Western Ghats, India, by a multigene approach." *Applied and Environmental Microbiology* 78, no. 12 (2012): 4458-4467.

## 
:::

## 2010

::: {style="text-align: justify"}
-   Salunke, Bipinchandra K., Rahul C. Salunkhe, **Dhiraj P. Dhotre**, Avinash B. Khandagale, Sandeep A. Walujkar, Gulab S. Kirwale, Hemant V. Ghate, Milind S. Patole, and Yogesh S. Shouche. "Diversity of Wolbachia in Odontotermes spp.(Termitidae) and Coptotermes heimi (Rhinotermitidae) using the multigene approach." *FEMS microbiology letters* 307, no. 1 (2010): 55-64.

-   Salunke, Bipinchandra K., **Dhiraj Dhotre**, and Sandeep A. Walujkar. "Diversity of Wolbachia in Odontotermes spp.(Termitidae) and Coptotermes heimi (Rhinotermitidae) using\..." (2010).
:::

## 2009

::: {style="text-align: justify"}
-   Patil, Deepak P., Santosh Atanur, **Dhiraj P. Dhotre**, D. Anantharam, Vineet S. Mahajan, Sandeep A. Walujkar, Rakesh K. Chandode et al. "Generation, annotation, and analysis of ESTs from midgut tissue of adult female Anopheles stephensi mosquitoes." *BMC genomics* 10, no. 1 (2009): 1-12.

-   Shouche, Y., A. Dighe, **D. Dhotre**, M. Patole, and D. Ranade. "The genus Selenomonas." *Bergey's Manual of Systematic Bacteriology* 1106 (2009): 1111.

## 
:::

## 2007

::: {style="text-align: justify"}
-   Vaishampayan, Parag A., **Dhiraj P. Dhotre**, Rakeshkumar P. Gupta, Pritesh Lalwani, Hemant Ghate, Milind S. Patole, and Yogesh S. Shouche. "Molecular evidence and phylogenetic affiliations of Wolbachia in cockroaches." *Molecular phylogenetics and evolution* 44, no. 3 (2007): 1346-1351.

-   Pandey, Prashant K., **Dhiraj P. Dhotre**, Mahesh S. Dharne, Ashok N. Khadse, Umesh I. Hiremath, Ravindra D. Chaudhari, Milind S. Patole, and Yogesh S. Shouche. "Evaluation of mitochondrial 12S rRNA gene in the identification of Panthera pardus fusca (Meyer, 1794) from field-collected scat samples in the Western Ghats, Maharashtra, India." *Current Science* (2007): 1129-1133.
:::
